import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 1 band "akad": y 4425..5907, height 1482 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 4425
export const BAND_HEIGHT = 1482

export const LAYERS: BandLayer[] = [
  { z: 22, id: '23:851', src: assets['akad/parts/23-851.webp'], x: 63, y: 748, w: 471, h: 706 },
  { z: 23, id: '22:822', src: assets['akad/parts/22-822.webp'], x: 24, y: 719, w: 548, h: 763 },
  { z: 40, id: '22:837', src: assets['akad/parts/22-837.webp'], x: 0, y: 884, w: 140, h: 301 },
  { z: 42, id: '22:838', src: assets['akad/parts/22-838.webp'], x: 464, y: 905, w: 132, h: 301 },
  { z: 138, id: '22:826', src: assets['akad/parts/22-826.webp'], x: 0, y: 713, w: 222, h: 322 },
  { z: 140, id: '22:846', src: assets['akad/parts/22-846.webp'], x: 0, y: 516, w: 167, h: 454 },
  { z: 141, id: '22:828', src: assets['akad/parts/22-828.webp'], x: 0, y: 776, w: 98, h: 196 },
  { z: 142, id: '22:832', src: assets['akad/parts/22-832.webp'], x: 502, y: 1053, w: 94, h: 196 },
  { z: 144, id: '22:827', src: assets['akad/parts/22-827.webp'], x: 419, y: 987, w: 177, h: 454 },
  { z: 146, id: '22:834', src: assets['akad/parts/22-834.webp'], x: 531, y: 1221, w: 65, h: 138 },
  { z: 148, id: '22:836', src: assets['akad/parts/22-836.webp'], x: 0, y: 881, w: 98, h: 138 },
  { z: 150, id: '22:839', src: assets['akad/parts/22-839.webp'], x: 502, y: 1027, w: 94, h: 96 },
  { z: 152, id: '22:842', src: assets['akad/parts/22-842.webp'], x: 146, y: 419, w: 304, h: 304 },
  { z: 156, id: '22:848', src: assets['akad/parts/22-848.webp'], x: 410, y: 540, w: 186, h: 365 },
  { z: 159, id: '22:849', src: assets['akad/parts/22-849.webp'], x: 0, y: 257, w: 211, h: 365 },
  { z: 166, id: '32:450', src: assets['akad/parts/32-450.webp'], x: 0, y: 1403, w: 75, h: 383 },
  { z: 167, id: '32:452', src: assets['akad/parts/32-452.webp'], x: 513, y: 1387, w: 83, h: 383 },
  { z: 263, id: '45:13', src: assets['akad/parts/45-13.webp'], x: 496, y: 371, w: 100, h: 246 },
  { z: 264, id: '52:2', src: assets['akad/parts/52-2.webp'], x: 0, y: 1270, w: 169, h: 309 },
  { z: 265, id: '52:3', src: assets['akad/parts/52-3.webp'], x: 438, y: 1270, w: 158, h: 309 },
  { z: 270, id: '54:33', src: assets['akad/parts/54-33.webp'], x: 63, y: 1193, w: 471, h: 261, a: 0.55, b: 'darken' },
  { z: 286, id: '54:20', src: assets['akad/parts/54-20.webp'], x: 0, y: 0, w: 596, h: 622 },
  { z: 287, id: '52:4', src: assets['akad/parts/52-4.webp'], x: 0, y: 111, w: 183, h: 366 },
  { z: 288, id: '52:5', src: assets['akad/parts/52-5.webp'], x: 419, y: 111, w: 177, h: 366 },
]
