import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 1 band "bismillah": y 1802..2161, height 359 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 1802
export const BAND_HEIGHT = 359

export const LAYERS: BandLayer[] = [
  { z: 45, id: '20:601', src: assets['bismillah/parts/20-601.webp'], x: 0, y: 215, w: 596, h: 344 },
  { z: 107, id: '19:571', src: assets['bismillah/parts/19-571.webp'], x: 0, y: 238, w: 344, h: 503 },
  { z: 109, id: '19:577', src: assets['bismillah/parts/19-577.webp'], x: 0, y: 262, w: 101, h: 526 },
  { z: 127, id: '20:593', src: assets['bismillah/parts/20-593.webp'], x: 503, y: 311, w: 93, h: 227 },
]
