import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 1 band "bride": y 2161..3163, height 1002 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 2161
export const BAND_HEIGHT = 1002

export const LAYERS: BandLayer[] = [
  { z: 11, id: '40:90', src: assets['bride/parts/40-90.webp'], x: 0, y: 265, w: 596, h: 854 },
  { z: 44, id: '20:640', src: assets['bride/parts/20-640.webp'], x: 0, y: 615, w: 53, h: 266 },
  { z: 46, id: '21:791', src: assets['bride/parts/21-791.webp'], x: 0, y: 862, w: 596, h: 344 },
  { z: 47, id: '19:574', src: assets['bride/parts/19-574.webp'], x: 0, y: 49, w: 596, h: 345 },
  { z: 49, id: '20:605', src: assets['bride/parts/20-605.webp'], x: 0, y: 0, w: 72, h: 194 },
  { z: 68, id: '19:572', src: assets['bride/parts/19-572.webp'], x: 155, y: 222, w: 342, h: 253 },
  { z: 70, id: '20:594', src: assets['bride/parts/20-594.webp'], x: 425, y: 37, w: 171, h: 253 },
  { z: 72, id: '20:584', src: assets['bride/parts/20-584.webp'], x: 0, y: 228, w: 291, h: 372 },
  { z: 97, id: '20:636', src: assets['bride/parts/20-636.webp'], x: 0, y: 685, w: 71, h: 150 },
  { z: 108, id: '20:623', src: assets['bride/parts/20-623.webp'], x: 244, y: 881, w: 352, h: 503 },
  { z: 110, id: '20:624', src: assets['bride/parts/20-624.webp'], x: 487, y: 905, w: 109, h: 526 },
  { z: 111, id: '19:579', src: assets['bride/parts/19-579.webp'], x: 0, y: 158, w: 92, h: 247 },
  { z: 113, id: '20:589', src: assets['bride/parts/20-589.webp'], x: 9, y: 252, w: 285, h: 285 },
  { z: 115, id: '20:586', src: assets['bride/parts/20-586.webp'], x: 255, y: 179, w: 141, h: 191 },
  { z: 117, id: '20:582', src: assets['bride/parts/20-582.webp'], x: 210, y: 338, w: 81, h: 81 },
  { z: 119, id: '20:583', src: assets['bride/parts/20-583.webp'], x: 0, y: 313, w: 80, h: 114 },
  { z: 121, id: '20:581', src: assets['bride/parts/20-581.webp'], x: 241, y: 290, w: 139, h: 139 },
  { z: 123, id: '20:591', src: assets['bride/parts/20-591.webp'], x: 101, y: 338, w: 101, h: 101 },
  { z: 125, id: '20:592', src: assets['bride/parts/20-592.webp'], x: 0, y: 152, w: 48, h: 227 },
  { z: 128, id: '20:633', src: assets['bride/parts/20-633.webp'], x: 0, y: 954, w: 85, h: 227 },
  { z: 131, id: '20:603', src: assets['bride/parts/20-603.webp'], x: 541, y: 106, w: 55, h: 176 },
  { z: 135, id: '20:649', src: assets['bride/parts/20-649.webp'], x: 462, y: 419, w: 134, h: 429 },
]
