import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 1 band "closing": y 11452..12818, height 1366 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 11452
export const BAND_HEIGHT = 1366

export const LAYERS: BandLayer[] = [
  { z: 15, id: '40:76', src: assets['closing/parts/40-76.webp'], x: 0, y: 0, w: 596, h: 1366 },
  { z: 16, id: '52:11', src: assets['closing/parts/52-11.webp'], x: 51, y: 586, w: 324, h: 324 },
  { z: 17, id: '52:12', src: assets['closing/parts/52-12.webp'], x: 250, y: 482, w: 324, h: 324 },
  { z: 18, id: '61:619', src: assets['closing/parts/61-619.webp'], x: 0, y: 335, w: 102, h: 254 },
  { z: 19, id: '61:620', src: assets['closing/parts/61-620.webp'], x: 503, y: 318, w: 94, h: 254 },
  { z: 20, id: '42:4', src: assets['closing/parts/42-4.webp'], x: 20, y: 72, w: 584, h: 480 },
  { z: 255, id: '40:80', src: assets['closing/parts/40-80.webp'], x: 58, y: 685, w: 501, h: 501 },
  { z: 256, id: '40:81', src: assets['closing/parts/40-81.webp'], x: 173, y: 496, w: 271, h: 427 },
  { z: 257, id: '40:84', src: assets['closing/parts/40-84.webp'], x: 206, y: 532, w: 205, h: 347 },
  { z: 258, id: '40:82', src: assets['closing/parts/40-82.webp'], x: 206, y: 532, w: 205, h: 347 },
  { z: 259, id: '40:86', src: assets['closing/parts/40-86.webp'], x: 263, y: 869, w: 91, h: 91 },
  { z: 281, id: '61:609', src: assets['closing/parts/61-609.webp'], x: 0, y: 142, w: 155, h: 377 },
  { z: 282, id: '61:610', src: assets['closing/parts/61-610.webp'], x: 0, y: 142, w: 155, h: 377 },
  { z: 283, id: '61:611', src: assets['closing/parts/61-611.webp'], x: 429, y: 142, w: 167, h: 377 },
  { z: 289, id: '42:2', src: assets['closing/parts/42-2.webp'], x: 0, y: 1315, w: 596, h: 51 },
]
