import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 1 band "countdown": y 1108..1802, height 694 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 1108
export const BAND_HEIGHT = 694

export const LAYERS: BandLayer[] = [
  { z: 9, id: '40:91', src: assets['countdown/parts/40-91.webp'], x: 0, y: 130, w: 596, h: 1006 },
  { z: 28, id: '26:8', src: assets['countdown/parts/26-8.webp'], x: 0, y: 0, w: 596, h: 641 },
  { z: 81, id: '16:397', src: assets['countdown/parts/16-397.webp'], x: 0, y: 518, w: 116, h: 562 },
  { z: 82, id: '16:398', src: assets['countdown/parts/16-398.webp'], x: 480, y: 518, w: 116, h: 562 },
  { z: 91, id: '16:491', src: assets['countdown/parts/16-491.webp'], x: 0, y: -124, w: 196, h: 368 },
  { z: 92, id: '16:493', src: assets['countdown/parts/16-493.webp'], x: 396, y: -124, w: 198, h: 368 },
  { z: 129, id: '20:599', src: assets['countdown/parts/20-599.webp'], x: 0, y: 444, w: 73, h: 243 },
  { z: 130, id: '20:598', src: assets['countdown/parts/20-598.webp'], x: 530, y: 444, w: 66, h: 243 },
]
