import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 1 band "dresscode": y 7034..7750, height 716 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 7034
export const BAND_HEIGHT = 716

export const LAYERS: BandLayer[] = [
  { z: 10, id: '54:24', src: assets['dresscode/parts/54-24.webp'], x: 0, y: 230, w: 596, h: 484 },
  { z: 27, id: '28:227', src: assets['dresscode/parts/28-227.webp'], x: 0, y: 356, w: 596, h: 441 },
  { z: 164, id: '28:226', src: assets['dresscode/parts/28-226.webp'], x: 94, y: 182, w: 422, h: 422 },
  { z: 168, id: '29:228', src: assets['dresscode/parts/29-228.webp'], x: 0, y: 499, w: 596, h: 217 },
  { z: 171, id: '29:233', src: assets['dresscode/parts/29-233.webp'], x: 0, y: 620, w: 592, h: 161 },
]
