import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 1 band "gallery": y 7750..8865, height 1115 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 7750
export const BAND_HEIGHT = 1115

export const LAYERS: BandLayer[] = [
  { z: 5, id: '45:9', src: assets['gallery/parts/45-9.webp'], x: 0, y: 53, w: 181, h: 355 },
  { z: 6, id: '45:10', src: assets['gallery/parts/45-10.webp'], x: 415, y: 53, w: 181, h: 355 },
  { z: 21, id: '31:287', src: assets['gallery/parts/31-287.webp'], x: 78, y: 286, w: 450, h: 224 },
  { z: 38, id: '52:6', src: assets['gallery/parts/52-6.webp'], x: 17, y: 405, w: 295, h: 295 },
  { z: 39, id: '52:8', src: assets['gallery/parts/52-8.webp'], x: 293, y: 405, w: 295, h: 295 },
  { z: 169, id: '29:235', src: assets['gallery/parts/29-235.webp'], x: 10, y: 0, w: 303, h: 161 },
  { z: 170, id: '31:316', src: assets['gallery/parts/31-316.webp'], x: 297, y: 0, w: 299, h: 161 },
  { z: 179, id: '31:289', src: assets['gallery/parts/31-289.webp'], x: 152, y: 312, w: 308, h: 403 },
  { z: 181, id: '31:295', src: assets['gallery/parts/31-295.webp'], x: 146, y: 728, w: 102, h: 119 },
  { z: 183, id: '31:301', src: assets['gallery/parts/31-301.webp'], x: 255, y: 728, w: 102, h: 119 },
  { z: 185, id: '31:304', src: assets['gallery/parts/31-304.webp'], x: 364, y: 728, w: 102, h: 119 },
  { z: 188, id: '31:314', src: assets['gallery/parts/31-314.webp'], x: 140, y: 512, w: 13, h: 25 },
  { z: 189, id: '31:315', src: assets['gallery/parts/31-315.webp'], x: 457, y: 512, w: 13, h: 25 },
  { z: 190, id: '31:318', src: assets['gallery/parts/31-318.webp'], x: 112, y: 901, w: 388, h: 213 },
  { z: 193, id: '31:309', src: assets['gallery/parts/31-309.webp'], x: 0, y: 973, w: 596, h: 188 },
]
