import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 1 band "gift": y 8865..9565, height 700 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 8865
export const BAND_HEIGHT = 700

export const LAYERS: BandLayer[] = [
  { z: 7, id: '45:11', src: assets['gift/parts/45-11.webp'], x: 460, y: 0, w: 136, h: 280, a: 0.4 },
  { z: 8, id: '45:12', src: assets['gift/parts/45-12.webp'], x: 0, y: 0, w: 140, h: 280, a: 0.85, b: 'screen' },
  { z: 205, id: '31:417', src: assets['gift/parts/31-417.webp'], x: 0, y: 20, w: 225, h: 466 },
  { z: 206, id: '31:422', src: assets['gift/parts/31-422.webp'], x: 361, y: 467, w: 235, h: 466 },
  { z: 207, id: '31:418', src: assets['gift/parts/31-418.webp'], x: 351, y: 20, w: 245, h: 466 },
  { z: 208, id: '31:423', src: assets['gift/parts/31-423.webp'], x: 0, y: 467, w: 235, h: 466 },
  { z: 209, id: '31:419', src: assets['gift/parts/31-419.webp'], x: 0, y: 385, w: 178, h: 277 },
  { z: 210, id: '31:421', src: assets['gift/parts/31-421.webp'], x: 417, y: 385, w: 179, h: 277 },
  { z: 212, id: '31:427', src: assets['gift/parts/31-427.webp'], x: 0, y: 385, w: 108, h: 238 },
  { z: 213, id: '32:457', src: assets['gift/parts/32-457.webp'], x: 0, y: 244, w: 78, h: 238 },
  { z: 215, id: '31:428', src: assets['gift/parts/31-428.webp'], x: 488, y: 385, w: 108, h: 238 },
  { z: 222, id: '32:458', src: assets['gift/parts/32-458.webp'], x: 518, y: 246, w: 78, h: 238 },
]
