import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 1 band "groom": y 3163..4021, height 858 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 3163
export const BAND_HEIGHT = 858

export const LAYERS: BandLayer[] = [
  { z: 3, id: '54:18', src: assets['groom/parts/54-18.webp'], x: 0, y: 659, w: 596, h: 481 },
  { z: 48, id: '20:607', src: assets['groom/parts/20-607.webp'], x: 0, y: 49, w: 596, h: 345 },
  { z: 50, id: '20:608', src: assets['groom/parts/20-608.webp'], x: 516, y: 0, w: 80, h: 194 },
  { z: 69, id: '20:609', src: assets['groom/parts/20-609.webp'], x: 91, y: 222, w: 342, h: 253 },
  { z: 71, id: '20:610', src: assets['groom/parts/20-610.webp'], x: 0, y: 37, w: 163, h: 253 },
  { z: 73, id: '20:611', src: assets['groom/parts/20-611.webp'], x: 297, y: 228, w: 299, h: 372 },
  { z: 112, id: '20:625', src: assets['groom/parts/20-625.webp'], x: 496, y: 158, w: 100, h: 247 },
  { z: 114, id: '20:626', src: assets['groom/parts/20-626.webp'], x: 294, y: 252, w: 285, h: 285 },
  { z: 116, id: '20:627', src: assets['groom/parts/20-627.webp'], x: 192, y: 179, w: 141, h: 191 },
  { z: 118, id: '20:628', src: assets['groom/parts/20-628.webp'], x: 297, y: 338, w: 81, h: 81 },
  { z: 120, id: '20:629', src: assets['groom/parts/20-629.webp'], x: 508, y: 313, w: 88, h: 114 },
  { z: 122, id: '20:630', src: assets['groom/parts/20-630.webp'], x: 208, y: 290, w: 139, h: 139 },
  { z: 124, id: '20:631', src: assets['groom/parts/20-631.webp'], x: 386, y: 338, w: 101, h: 101 },
  { z: 126, id: '20:632', src: assets['groom/parts/20-632.webp'], x: 540, y: 152, w: 56, h: 227 },
  { z: 132, id: '20:634', src: assets['groom/parts/20-634.webp'], x: 0, y: 106, w: 47, h: 176 },
  { z: 216, id: '32:447', src: assets['groom/parts/32-447.webp'], x: 0, y: 608, w: 237, h: 429 },
  { z: 217, id: '32:449', src: assets['groom/parts/32-449.webp'], x: 356, y: 608, w: 240, h: 429 },
]
