import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 1 band "hero": y 0..1108, height 1108 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 0
export const BAND_HEIGHT = 1108

export const LAYERS: BandLayer[] = [
  { z: 12, id: '40:88', src: assets['hero/parts/40-88.webp'], x: 0, y: 0, w: 596, h: 829 },
  { z: 13, id: '54:21', src: assets['hero/parts/54-21.webp'], x: 0, y: 555, w: 596, h: 455 },
  { z: 14, id: '40:89', src: assets['hero/parts/40-89.webp'], x: 4, y: 64, w: 584, h: 372 },
  { z: 51, id: '18:502', src: assets['hero/parts/18-502.webp'], x: 0, y: 623, w: 596, h: 673 },
  { z: 52, id: '15:194', src: assets['hero/parts/15-194.webp'], x: 0, y: 494, w: 158, h: 551 },
  { z: 53, id: '15:196', src: assets['hero/parts/15-196.webp'], x: 435, y: 494, w: 161, h: 551 },
  { z: 54, id: '15:91', src: assets['hero/parts/15-91.webp'], x: 80, y: 409, w: 437, h: 688 },
  { z: 55, id: '15:94', src: assets['hero/parts/15-94.webp'], x: 80, y: 409, w: 437, h: 688 },
  { z: 56, id: '15:95', src: assets['hero/parts/15-95.webp'], x: 80, y: 409, w: 437, h: 688 },
  { z: 57, id: '20:647', src: assets['hero/parts/20-647.webp'], x: 0, y: 409, w: 596, h: 699 },
  { z: 58, id: '15:190', src: assets['hero/parts/15-190.webp'], x: 29, y: 600, w: 92, h: 162 },
  { z: 59, id: '15:192', src: assets['hero/parts/15-192.webp'], x: 471, y: 600, w: 92, h: 162 },
  { z: 63, id: '15:82', src: assets['hero/parts/15-82.webp'], x: 25, y: 691, w: 84, h: 314 },
  { z: 64, id: '15:96', src: assets['hero/parts/15-96.webp'], x: 491, y: 690, w: 84, h: 314 },
  { z: 65, id: '15:85', src: assets['hero/parts/15-85.webp'], x: 31, y: 797, w: 110, h: 209 },
  { z: 66, id: '15:97', src: assets['hero/parts/15-97.webp'], x: 459, y: 796, w: 110, h: 209 },
  { z: 67, id: '15:176', src: assets['hero/parts/15-176.webp'], x: 0, y: 269, w: 230, h: 290 },
  { z: 74, id: '15:185', src: assets['hero/parts/15-185.webp'], x: 378, y: 265, w: 218, h: 290 },
  { z: 75, id: '15:179', src: assets['hero/parts/15-179.webp'], x: 0, y: 209, w: 109, h: 173 },
  { z: 76, id: '15:186', src: assets['hero/parts/15-186.webp'], x: 499, y: 205, w: 97, h: 173 },
  { z: 77, id: '15:182', src: assets['hero/parts/15-182.webp'], x: 0, y: 258, w: 86, h: 335 },
  { z: 78, id: '15:187', src: assets['hero/parts/15-187.webp'], x: 522, y: 254, w: 74, h: 335 },
  { z: 79, id: '15:184', src: assets['hero/parts/15-184.webp'], x: 0, y: 314, w: 105, h: 166 },
  { z: 80, id: '15:188', src: assets['hero/parts/15-188.webp'], x: 503, y: 310, w: 93, h: 166 },
  { z: 191, id: '31:321', src: assets['hero/parts/31-321.webp'], x: 0, y: 0, w: 466, h: 227 },
  { z: 192, id: '31:322', src: assets['hero/parts/31-322.webp'], x: 250, y: 0, w: 346, h: 375 },
  { z: 223, id: '32:459', src: assets['hero/parts/32-459.webp'], x: 244, y: 347, w: 124, h: 132 },
  { z: 266, id: '52:10', src: assets['hero/parts/52-10.webp'], x: 468, y: 980, w: 128, h: 255 },
  { z: 267, id: '52:9', src: assets['hero/parts/52-9.webp'], x: 0, y: 980, w: 128, h: 255 },
]
