import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 1 band "quote": y 4021..4425, height 404 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 4021
export const BAND_HEIGHT = 404

export const LAYERS: BandLayer[] = [
  { z: 4, id: '54:17', src: assets['quote/parts/54-17.webp'], x: 0, y: 0, w: 596, h: 481 },
  { z: 134, id: '23:882', src: assets['quote/parts/23-882.webp'], x: 101, y: 50, w: 396, h: 598 },
  { z: 163, id: '24:919', src: assets['quote/parts/24-919.webp'], x: 60, y: 391, w: 156, h: 166 },
  { z: 165, id: '24:921', src: assets['quote/parts/24-921.webp'], x: 380, y: 391, w: 156, h: 166 },
  { z: 230, id: '20:762', src: assets['quote/parts/20-762.webp'], x: 73, y: 302, w: 92, h: 162 },
  { z: 231, id: '20:763', src: assets['quote/parts/20-763.webp'], x: 433, y: 308, w: 92, h: 162 },
]
