import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 1 band "resepsi": y 5907..7034, height 1127 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 5907
export const BAND_HEIGHT = 1127

export const LAYERS: BandLayer[] = [
  { z: 24, id: '29:241', src: assets['resepsi/parts/29-241.webp'], x: 62, y: 329, w: 471, h: 706 },
  { z: 25, id: '29:242', src: assets['resepsi/parts/29-242.webp'], x: 24, y: 300, w: 548, h: 763 },
  { z: 30, id: '54:42', src: assets['resepsi/parts/54-42.webp'], x: 62, y: 781, w: 471, h: 261, a: 0.55 },
  { z: 41, id: '29:243', src: assets['resepsi/parts/29-243.webp'], x: 456, y: 465, w: 140, h: 301 },
  { z: 43, id: '29:244', src: assets['resepsi/parts/29-244.webp'], x: 0, y: 486, w: 132, h: 301 },
  { z: 139, id: '29:245', src: assets['resepsi/parts/29-245.webp'], x: 374, y: 294, w: 222, h: 322 },
  { z: 143, id: '29:248', src: assets['resepsi/parts/29-248.webp'], x: 0, y: 634, w: 94, h: 196 },
  { z: 145, id: '29:249', src: assets['resepsi/parts/29-249.webp'], x: 0, y: 568, w: 177, h: 454 },
  { z: 147, id: '29:250', src: assets['resepsi/parts/29-250.webp'], x: 0, y: 802, w: 65, h: 138 },
  { z: 149, id: '29:251', src: assets['resepsi/parts/29-251.webp'], x: 498, y: 462, w: 98, h: 138 },
  { z: 151, id: '29:252', src: assets['resepsi/parts/29-252.webp'], x: 0, y: 608, w: 94, h: 96 },
  { z: 153, id: '29:253', src: assets['resepsi/parts/29-253.webp'], x: 146, y: 0, w: 304, h: 304 },
  { z: 157, id: '29:254', src: assets['resepsi/parts/29-254.webp'], x: 0, y: 121, w: 186, h: 365 },
  { z: 158, id: '24:897', src: assets['resepsi/parts/24-897.webp'], x: 0, y: 174, w: 169, h: 365, a: 0.2, b: 'screen' },
  { z: 172, id: '29:274', src: assets['resepsi/parts/29-274.webp'], x: 0, y: 97, w: 75, h: 292 },
  { z: 218, id: '29:246', src: assets['resepsi/parts/29-246.webp'], x: 429, y: 97, w: 167, h: 454 },
  { z: 219, id: '29:247', src: assets['resepsi/parts/29-247.webp'], x: 515, y: 345, w: 81, h: 196 },
]
