import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 1 band "rsvp": y 10763..11452, height 689 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 10763
export const BAND_HEIGHT = 689

export const LAYERS: BandLayer[] = [
  { z: 26, id: '40:79', src: assets['rsvp/parts/40-79.webp'], x: 0, y: 583, w: 95, h: 383 },
  { z: 242, id: '35:534', src: assets['rsvp/parts/35-534.webp'], x: 0, y: 0, w: 151, h: 180 },
  { z: 243, id: '40:73', src: assets['rsvp/parts/40-73.webp'], x: 433, y: 47, w: 163, h: 180 },
  { z: 252, id: '40:71', src: assets['rsvp/parts/40-71.webp'], x: 0, y: 142, w: 225, h: 418 },
  { z: 253, id: '40:72', src: assets['rsvp/parts/40-72.webp'], x: 371, y: 146, w: 225, h: 418 },
  { z: 254, id: '40:77', src: assets['rsvp/parts/40-77.webp'], x: 511, y: 572, w: 85, h: 383 },
  { z: 279, id: '61:606', src: assets['rsvp/parts/61-606.webp'], x: 0, y: 491, w: 43, h: 195 },
  { z: 280, id: '61:607', src: assets['rsvp/parts/61-607.webp'], x: 553, y: 491, w: 43, h: 195 },
]
