import { assets } from '../bandAssets'

// Generated by scripts/gen_band.py — do not hand-edit.
// Figma Frame 1 band "wishes": y 9565..10763, height 1198 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
//
// Positions are NOT Figma's reported bounds — see "exported bounds are not node bounds"
// in SLICING.md. Regenerate rather than nudging numbers by hand.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 9565
export const BAND_HEIGHT = 1198

export const LAYERS: BandLayer[] = [
  { z: 1, id: '61:614', src: assets['wishes/parts/61-614.webp'], x: 0, y: 1101, w: 596, h: 308 },
  { z: 2, id: '61:603', src: assets['wishes/parts/61-603.webp'], x: 0, y: 978, w: 596, h: 477 },
  { z: 211, id: '31:424', src: assets['wishes/parts/31-424.webp'], x: 0, y: 99, w: 108, h: 238 },
  { z: 214, id: '31:426', src: assets['wishes/parts/31-426.webp'], x: 488, y: 99, w: 108, h: 238 },
  { z: 220, id: '32:454', src: assets['wishes/parts/32-454.webp'], x: 530, y: 0, w: 66, h: 176 },
  { z: 221, id: '32:456', src: assets['wishes/parts/32-456.webp'], x: 0, y: 0, w: 66, h: 176 },
  { z: 284, id: '61:615', src: assets['wishes/parts/61-615.webp'], x: 265, y: 952, w: 65, h: 82 },
]
